### ISSUE TITLE
[BUG] Sound command not working

### ISSUE THREAD

**Issue by OreoKirby** [nulli0n/LootConomy-spigot#2]
### Minecraft's Version

Paper version 1.21-91

### Plugin's Version

LootConomy 2.0.4

### Describe the bug

When attempting to use the SOUND command the plugin is throwing an error and not functioning properly.

### To Reproduce

1. Run the in-game command `/lootcnonomy sound`

### Additional Information

```
[15:56:14 INFO]: OreoKirby issued server command: /lootconomy sound
[15:56:14 ERROR]: Command exception: /lootconomy sound
java.lang.NullPointerException: Cannot invoke "su.nightexpress.nightcore.command.experimental.node.DirectExecutor.execute(su.nightexpress.nightcore.command.experimental.CommandContext, su.nightexpress.nightcore.command.experimental.argument.ParsedArguments)" because "this.executor" is null
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.node.DirectNode.execute(DirectNode.java:53) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.node.DirectNode.onRun(DirectNode.java:145) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.node.CommandNode.run(CommandNode.java:53) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.node.ChainedNode.onRun(ChainedNode.java:69) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.node.CommandNode.run(CommandNode.java:53) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.experimental.RootCommand.onCommand(RootCommand.java:99) ~[nightcore-2.6.2.jar:?]
        at nightcore-2.6.2.jar/su.nightexpress.nightcore.command.impl.WrappedCommand.execute(WrappedCommand.java:62) ~[nightcore-2.6.2.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1533) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1510) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1503) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1462) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1469) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1314) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by nulli0n** [comment]
Fixed in the latest version.
